os:
  - Visual Studio 2015

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release
  
branches:
  only:
    - master

install:
  - git clone https://github.com/siquel/kaluketju

build:
  project: build/kulma.sln
