language: cpp

compiler:
 - clang
 - gcc

before_script:
    git clone https://github.com/siquel/kaluketju

script:
    - if [ "$CXX" == "clang++" ]; then make linux-clang && .build/linux64_clang/bin/unit_testDebug; fi
    - if [ "$CXX" == "g++-4.8" ]; then make linux-gcc && .build/linux64_gcc/bin/unit_testDebug; fi
    - $CXX --version

branches:
  only:
    - master

notifications:
  email: false

install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8