language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: COMPILER=g++-5

#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
#          packages: ['clang-3.8']
#      env: COMPILER=clang++-3.8

before_script:
    git clone https://github.com/siquel/kaluketju

script:
    - if [ "$CXX" == "clang++" ]; then make CXX=$COMPILER linux-clang && .build/linux64_clang/bin/unit_testDebug; fi
    - if [ "$CXX" == "g++" ]; then make CXX=$COMPILER linux-gcc && .build/linux64_gcc/bin/unit_testDebug; fi
    - $COMPILER --version

branches:
  only:
    - master

notifications:
  email: false
